[package]
name = "my_dubious_uniform_resource_locator_shortener"
version = "0.0.1"
authors = ["Zack M. Davis <code@zackmdavis.net>"]

[dependencies]
diesel = "0.5"
diesel_codegen = { version = "0.5", default-features = false, features = ["nightly", "sqlite"] }
hyper = "0.7"
pencil = "0.1"
